name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t docker.pkg.github.com/USERNAME/REPOSITORY/IMAGE_NAME:TAG .

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Push Docker Image
      run: docker push docker.pkg.github.com/USERNAME/REPOSITORY/IMAGE_NAME:TAG
